---
- name: Create monitoring directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_data_dir }}/prometheus"
    - "{{ docker_data_dir }}/prometheus/data"
    - "{{ docker_data_dir }}/grafana"
    - "{{ docker_data_dir }}/grafana/data"
    - "{{ docker_data_dir }}/grafana/provisioning"
    - "{{ docker_data_dir }}/grafana/provisioning/dashboards"
    - "{{ docker_data_dir }}/grafana/provisioning/datasources"
    - "{{ docker_data_dir }}/alertmanager"

- name: Set proper ownership for monitoring directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0755'
    recurse: yes
  loop:
    - { path: "{{ docker_data_dir }}/prometheus/data", owner: "65534", group: "65534" }
    - { path: "{{ docker_data_dir }}/grafana/data", owner: "472", group: "472" }

- name: Create Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ docker_data_dir }}/prometheus/prometheus.yml"
    mode: '0644'

- name: Create Prometheus rules
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_data_dir }}/prometheus/{{ item }}"
    mode: '0644'
  loop:
    - node-exporter-rules.yml
    - docker-rules.yml

- name: Create Alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "{{ docker_data_dir }}/alertmanager/alertmanager.yml"
    mode: '0644'

- name: Create Grafana datasource configuration
  template:
    src: datasources.yml.j2
    dest: "{{ docker_data_dir }}/grafana/provisioning/datasources/datasources.yml"
    mode: '0644'

- name: Create Grafana dashboard configuration
  template:
    src: dashboards.yml.j2
    dest: "{{ docker_data_dir }}/grafana/provisioning/dashboards/dashboards.yml"
    mode: '0644'

- name: Download Grafana dashboards
  get_url:
    url: "{{ item.url }}"
    dest: "{{ docker_data_dir }}/grafana/provisioning/dashboards/{{ item.name }}.json"
    mode: '0644'
  loop:
    - name: node-exporter
      url: "https://raw.githubusercontent.com/rfmoz/grafana-dashboards/master/prometheus/node-exporter-full.json"
    - name: docker-monitoring
      url: "https://raw.githubusercontent.com/stefanprodan/dockprom/master/grafana/provisioning/dashboards/docker-monitoring.json"

- name: Create monitoring stack compose file
  template:
    src: monitoring-stack.yml.j2
    dest: "{{ docker_compose_dir }}/monitoring-stack.yml"
    mode: '0644'

- name: Deploy monitoring stack
  docker_stack:
    name: monitoring
    compose:
      - "{{ docker_compose_dir }}/monitoring-stack.yml"
    state: present

- name: Wait for Grafana to be ready
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:3000/api/health"
    method: GET
    status_code: 200
  retries: 30
  delay: 10
  register: grafana_health
  until: grafana_health.status == 200

- name: Display monitoring information
  debug:
    msg: |
      Monitoring stack deployed successfully!
      Grafana: http://{{ ansible_default_ipv4.address }}:3000
      Prometheus: http://{{ ansible_default_ipv4.address }}:9090
      AlertManager: http://{{ ansible_default_ipv4.address }}:9093
      
      Default Grafana credentials: admin / {{ grafana_admin_password }}