---
- name: Check if Swarm is already initialized
  docker_swarm_info:
  register: swarm_info
  ignore_errors: yes

- name: Initialize Docker Swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ docker_swarm_addr }}"
    listen_addrs:
      - "{{ docker_swarm_addr }}:{{ docker_swarm_port }}"
  register: swarm_init
  when: not swarm_info.can_talk_to_docker or not swarm_info.docker_swarm_active

- name: Create overlay networks
  docker_network:
    name: "{{ item }}"
    driver: overlay
    attachable: yes
    scope: swarm
  loop:
    - traefik-public
    - portainer-agent

- name: Label manager nodes
  docker_node:
    hostname: "{{ ansible_hostname }}"
    labels:
      node.role: manager
  when: node_role == 'manager'

- name: Create stack deployment script
  template:
    src: deploy-stacks.sh.j2
    dest: /usr/local/bin/deploy-stacks.sh
    mode: '0755'
