---
- name: Create Traefik directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_data_dir }}/traefik"
    - "{{ docker_data_dir }}/traefik/logs"

- name: Generate basic auth hash for admin user
  shell: |
    docker run --rm httpd:2.4-alpine htpasswd -nbB admin "{{ traefik_admin_password }}" | sed 's/\$/\$\$/g'
  register: admin_auth_hash
  changed_when: false

- name: Create Traefik stack compose file from template
  template:
    src: traefik-stack.yml.j2
    dest: "{{ docker_compose_dir }}/traefik-stack.yml"
    mode: '0644'
  vars:
    traefik_admin_auth_hash: "{{ admin_auth_hash.stdout }}"

- name: Deploy Traefik stack
  docker_stack:
    name: traefik
    compose:
      - "{{ docker_compose_dir }}/traefik-stack.yml"
    state: present

- name: Wait for Traefik to be ready
  uri:
    url: "https://traefik.{{ base_domain }}/ping"
    method: GET
    status_code: 200
    validate_certs: false
  retries: 30
  delay: 10
  register: traefik_health
  until: traefik_health.status == 200

- name: Display Traefik information
  debug:
    msg: |
      Traefik deployed successfully!
      Dashboard: https://traefik.{{ base_domain }}
      API endpoint: https://traefik.{{ base_domain }}/api
      Test service: https://whoami.{{ base_domain }}