---
- name: Create monitoring directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
  loop:
    - path: "{{ docker_data_dir }}/grafana"
      owner: 472
      group: 472
    - path: "{{ docker_data_dir }}/grafana/plugins"
      owner: 472
      group: 472
    - path: "{{ docker_data_dir }}/loki"
      owner: 10001
      group: 10001
    - path: "{{ docker_data_dir }}/loki/rules"
      owner: 10001
      group: 10001
    - path: "{{ docker_data_dir }}/alloy"

- name: Create Alloy configuration
  ansible.builtin.template:
    src: alloy-config.alloy.j2
    dest: "{{ docker_data_dir }}/alloy/config.alloy"
    mode: '0644'

- name: Create monitoring stack compose file
  ansible.builtin.template:
    src: monitoring-stack.yml.j2
    dest: "{{ docker_compose_dir }}/monitoring-stack.yml"
    mode: '0644'

- name: Ensure monitoring overlay network exists
  community.docker.docker_network:
    name: monitoring
    driver: overlay
    attachable: true
    scope: swarm

- name: Deploy monitoring stack
  community.docker.docker_stack:
    name: monitoring
    compose:
      - "{{ docker_compose_dir }}/monitoring-stack.yml"
    state: present

- name: Wait for Grafana to be ready
  ansible.builtin.uri:
    url: "https://{{ grafana_domain }}"
    method: GET
    status_code: 200
    validate_certs: false
  retries: 30
  delay: 10
  register: monitoring_grafana_health
  until: monitoring_grafana_health.status == 200

- name: Display Monitoring information
  ansible.builtin.debug:
    msg: |
      Monitoring stack deployed successfully!
      Grafana: https://{{ grafana_domain }}
