# This file should be encrypted with ansible-vault
# Example: ansible-vault encrypt ansible/vars/secrets.yml

# Traefik
traefik_admin_password: "changeme"

# MLOps Stack
mlflow_postgres_password: "changeme"
minio_root_user: "minioadmin"
minio_root_password: "changeme"
