---
- name: Create Portainer directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_data_dir }}/portainer"

- name: Create Portainer stack compose file
  template:
    src: portainer-stack.yml.j2
    dest: "{{ docker_compose_dir }}/portainer-stack.yml"
    mode: '0644'

- name: Deploy Portainer stack
  docker_stack:
    name: portainer
    compose:
      - "{{ docker_compose_dir }}/portainer-stack.yml"
    state: present

- name: Display Portainer information
  debug:
    msg: |
      Portainer deployed successfully!
      Web UI: http://{{ ansible_default_ipv4.address }}:9000
      Default credentials: admin / {{ portainer_admin_password }}