---
# defaults file for mlops role

# Domains
mlops_domain: "mlflow.{{ base_domain }}"
minio_domain: "minio.{{ base_domain }}"

# Image versions
mlflow_image: "ghcr.io/mlflow/mlflow"
mlflow_version: "v2.14.1"
postgres_image: "postgres"
postgres_version: "16"
minio_image: "minio/minio"
minio_version: "RELEASE.2024-07-23T09-23-27Z"

# MLflow configuration
mlflow_backend_store_uri: "postgresql://mlflow:{{ mlflow_postgres_password }}@postgres:5432/mlflow"
mlflow_default_artifact_root: "s3://mlflow/"

# MinIO configuration
minio_root_user: "{{ minio_root_user }}"
minio_root_password: "{{ minio_root_password }}"
minio_bucket_name: "mlflow"

# PostgreSQL configuration
postgres_user: "mlflow"
postgres_password: "{{ mlflow_postgres_password }}"
postgres_db: "mlflow"
