---
- name: Create MLOps stack compose file
  template:
    src: mlops-stack.yml.j2
    dest: "{{ docker_compose_dir }}/mlops-stack.yml"
    mode: '0644'

- name: Deploy MLOps stack
  docker_stack:
    name: mlops
    compose:
      - "{{ docker_compose_dir }}/mlops-stack.yml"
    state: present

- name: Wait for PostgreSQL to be ready
  wait_for:
    host: "127.0.0.1"
    port: 5432
    delay: 5
    timeout: 60
  run_once: true

- name: Install psycopg2 for PostgreSQL
  pip:
    name: psycopg2-binary
    state: present
  become: yes
  run_once: true
  when: ansible_python_interpreter is defined

- name: Ensure shared PostgreSQL database exists
  community.postgresql.postgresql_db:
    name: "{{ shared_postgres_db }}"
    login_host: "127.0.0.1"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
  run_once: true

- name: Ensure shared PostgreSQL user exists
  community.postgresql.postgresql_user:
    name: "{{ shared_postgres_user }}"
    password: "{{ shared_postgres_password }}"
    db: "{{ shared_postgres_db }}"
    priv: "ALL"
    login_host: "127.0.0.1"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
  run_once: true

- name: Wait for MLflow to be ready
  uri:
    url: "https://{{ mlops_domain }}"
    method: GET
    status_code: 200
    validate_certs: false
  retries: 30
  delay: 10
  register: mlflow_health
  until: mlflow_health.status == 200
  no_log: true

- name: Display MLOps information
  debug:
    msg: |
      MLOps Stack deployed successfully!
      MLflow UI: https://{{ mlops_domain }}
      MinIO Console: https://{{ minio_domain }}
      Shared PostgreSQL Host: {{ inventory_hostname }}:5432
      Shared Database: {{ shared_postgres_db }}
      Shared User: {{ shared_postgres_user }}
